 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
   args:
   - gcloud
   - functions
   - deploy
   - <your-function-name> # For example: my-budget-function
   - --region=us-central1 # Choose the region where you would like the function deployed
   - --source=./function-source/
   - --trigger-topic=<your pub/sub topic>
   - --entry-point=process # Function entry point  
   - --runtime=nodejs20
